#!/usr/bin/env python3
"""
Graph JSON Generator for Integration Tests

This tool compiles Flow script (input.txt) files into graph.json files.
Currently creates placeholders - will be integrated with actual compiler.
"""
import sys
import json
from pathlib import Path

def generate_placeholder_graph(input_file: Path, output_file: Path) -> bool:
    """Generate a placeholder graph.json until compiler integration is complete."""
    try:
        with open(input_file, 'r') as f:
            source = f.read()
        
        # Create a placeholder that indicates this needs to be generated
        placeholder = {
            "_note": "This graph.json needs to be generated by running the compiled test",
            "source_file": str(input_file.relative_to(input_file.parents[2])),
            "status": "pending_generation"
        }
        
        with open(output_file, 'w') as f:
            json.dump(placeholder, f, indent=2)
        
        return True
        
    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        return False

def main():
    if len(sys.argv) < 2:
        print("Usage: generate_graph_json.py <test_case_dir> [...]")
        sys.exit(1)
    
    success = 0
    for test_dir_arg in sys.argv[1:]:
        test_dir = Path(test_dir_arg)
        input_file = test_dir / "input.txt"
        output_file = test_dir / "expected" / "graph.json"
        
        if not input_file.exists():
            print(f"Skip {test_dir.name}: no input.txt")
            continue
        
        output_file.parent.mkdir(parents=True, exist_ok=True)
        if generate_placeholder_graph(input_file, output_file):
            print(f"Created placeholder: {test_dir.name}/expected/graph.json")
            success += 1
    
    print(f"\nCreated {success} placeholders")
    return 0

if __name__ == "__main__":
    sys.exit(main())
